name: Continious Integration / Continious Deployment

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  eslint:
    name: 'Eslint pipeline'
    runs-on: ubuntu-latest
    needs: 'Setup'

    steps:
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn install

      - name: Eslint check
        run: |
          echo "Checking Eslint"
          yarn run check-lint
