name: Continuous Integration

on:
  push:
    branches:
      - '**'

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  tests:
    name: 'Integration tests'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn install
      - run: |
          echo "Running tests"
          yarn test

  eslint:
    name: 'Eslint Pipeline'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn install
      - name: Eslint check
        run: |
          echo "Checking Eslint"
          yarn run check-lint

  format:
    name: 'Format Pipeline'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn install
      - name: Format check
        run: |
          echo "Checking Format"
          yarn run check-format

  types:
    name: 'Types Pipeline'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn install
      - name: Types check
        run: |
          echo "Checking Typescript"
          yarn run check-types
