name: Continious Integration / Continious Deployment

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  tests:
    name: 'Integration tests'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn install

      - run: |
          echo "Running tests"
          yarn test

  eslint:
    name: 'Eslint Pipeline'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "Running tests"
          yarn test

      - name: Eslint check
        run: |
          echo "Checking Eslint"
          yarn run check-lint
