name: Continous Integration

on:
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
  eslint:
    name: 'Eslint pipeline'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - run: yarn check-lint
